locaste/decide/base/urls.py
urlpatterns = []

locaste/decide/decide/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from rest_framework_swagger.views import get_swagger_view
from authentication.views import IndexView


schema_view = get_swagger_view(title='Decide API')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('doc/', schema_view),
    path('accounts/', include('allauth.urls')),
    path('rest-auth/',include('rest_auth.urls')),
    path('authentication/', include('authentication.urls')),
    path('voting/', include('voting.urls')),
    path('',IndexView.as_view(),name='index')
]

for module in settings.MODULES:
    urlpatterns += [
        path('{}/'.format(module), include('{}.urls'.format(module)))
    ]

locaste/decide/voting/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.VotingView.as_view(), name='voting'),
    path('create/', views.votingForm, name='create_voting'),
    path('<int:voting_id>/', views.VotingUpdate.as_view(), name='voting'),
    path('list/', views.VotingList.as_view(), name='voting_list'),
    path('statistics/', views.voting_statistics, name='voting_statistics')
]

locaste/decide/voting/models.py
from django.db import models
from django.contrib.postgres.fields import JSONField
import json
import os
from base import mods
from base.models import Auth, Key


GENRES_CHOICES = [
    ("Male", "Male"),
    ("Female", "Female"),
    ("Other", "Other"),
]

QUESTIONS_TYPES = [
    ("Range", "Range"),
    ("Percentage", "Percentage"),
    ("Normal", "Normal"),
]

TALLY_TYPES = [
    ("SAINTELAGUE", "SAINTELAGUE"),
    ("DHONDT", "DHONDT"),
    ("MAJORREST", "MAJORREST"),
    ("SAINTELAGUEMOD", "SAINTELAGUEMOD"),
]


class Question(models.Model):
    desc = models.TextField()
    type = models.TextField(blank=True, null=True, default=("Normal", "Normal"), choices=QUESTIONS_TYPES)

    def __str__(self):
        return self.desc


class QuestionOption(models.Model):
    question = models.ForeignKey(Question, related_name='options', on_delete=models.CASCADE)
    number = models.PositiveIntegerField(blank=True, null=True)
    range = models.PositiveIntegerField(blank=True, null=True)
    option = models.TextField(blank=True, null=True)
    percentage = models.DecimalField(blank=True, null=True,decimal_places=2,max_digits=3)

    def save(self):
        if not self.number:
            self.number = self.question.options.count() + 2
        return super().save()

    def __str__(self):
        if self.number != None:
            return '{} ({})'.format(self.number, self.number)
        elif self.range != None:
            return '{} ({})'.format(self.range, self.number)
        else :
            return '{} ({})'.format(self.option, self.number)






class Voting(models.Model):
    name = models.CharField(max_length=200)
    desc = models.TextField(blank=True, null=True)
    image_header = models.CharField(max_length=200,blank=True, null=True)
    question = models.ManyToManyField(Question, related_name='voting_questions')

    start_date = models.DateTimeField(blank=True, null=True)
    end_date = models.DateTimeField(blank=True, null=True)
    gender = models.TextField(blank=True, null=True, choices=GENRES_CHOICES)
    min_age = models.IntegerField(blank=True, null=True)
    max_age = models.IntegerField(blank=True, null=True)
    seats = models.IntegerField(blank=True, null=True)
    tally_type = models.TextField(blank=True, null=True, choices=TALLY_TYPES)

    pub_key = models.OneToOneField(Key, related_name='voting', blank=True, null=True, on_delete=models.SET_NULL)
    auths = models.ManyToManyField(Auth, related_name='votings')

    custom_url = models.CharField(max_length=100, blank=True)
    public_voting = models.BooleanField(default=False)

    tally = JSONField(blank=True, null=True)
    postproc = JSONField(blank=True, null=True)

    def create_pubkey(self):
        if self.pub_key or not self.auths.count():
            return

        auth = self.auths.first()
        data = {
            "voting": self.id,
            "auths": [ {"name": a.name, "url": a.url} for a in self.auths.all() ],
        }
        key = mods.post('mixnet', baseurl=auth.url, json=data)
        pk = Key(p=key["p"], g=key["g"], y=key["y"])
        pk.save()
        self.pub_key = pk
        self.save()

    def get_votes(self, token=''):
        # gettings votes from store
        votes = mods.get('store', params={'voting_id': self.id}, HTTP_AUTHORIZATION='Token ' + token)
        # anon votes
        return [[i['a'], i['b']] for i in votes]

    def get_voters(self, token=''):
        # getting the len of the census of the current voting
        census = mods.get('census', params={'voting_id': self.id}, HTTP_AUTHORIZATION='Token ' + token)
        return len(census['voters'])

    def tally_votes(self, token=''):
        '''
        The tally is a shuffle and then a decrypt
        '''

        votes = self.get_votes(token)

        auth = self.auths.first()
        shuffle_url = "/shuffle/{}/".format(self.id)
        decrypt_url = "/decrypt/{}/".format(self.id)
        auths = [{"name": a.name, "url": a.url} for a in self.auths.all()]

        # first, we do the shuffle
        data = { "msgs": votes }
        response = mods.post('mixnet', entry_point=shuffle_url, baseurl=auth.url, json=data,
                response=True)
        if response.status_code != 200:
            # TODO: manage error
            pass

        # then, we can decrypt that
        data = {"msgs": response.json()}
        response = mods.post('mixnet', entry_point=decrypt_url, baseurl=auth.url, json=data,
                response=True)

        if response.status_code != 200:
            # TODO: manage error
            pass
        self.tally = response.json()
        self.save()
        census = self.get_voters(token)

        return self.do_postproc(census)

    def do_postproc(self, census):
        tally = self.tally
        options = []
        for q in self.question.all():
            options.extend(q.options.all())

        opts = []
        for opt in options:
            if isinstance(tally, list):
                votes = tally.count(opt.number)
            else:
                votes = 0
            opts.append({
                'option': opt.option,
                'number': opt.number,
                'votes': votes
            })

        data = {'type': self.tally_type, 'options': opts, 'census': census}
        print(data)
        directory = "voting/tallies/"
        if not os.path.exists(directory):
            os.makedirs(directory)
        file_name = 'tally_voting'+str(self.id)
        with open(directory+file_name+'.json', 'w') as outfile:
            json.dump(data, outfile)

        postp = mods.post('postproc', json=data)

        self.postproc = postp
        self.save()

        return directory+file_name+'.json'

    def __str__(self):
        return self.name

locaste/decide/base/views.py
from django.shortcuts import render

# Create your views here.

locaste/decide/voting/views.py
import django_filters.rest_framework
from django.conf import settings
from django.utils import timezone
from django.shortcuts import get_object_or_404, render
from rest_framework import generics, status
from rest_framework.response import Response
from django.views import generic
from django.db import connection

from .models import Question, QuestionOption, Voting
from .serializers import VotingSerializer
from base.perms import UserIsStaff
from base.models import Auth
from .forms.forms import VotingForm, QuestionForm, QuestionOptionForm, AuthForm
from django.db import transaction
import json
import urllib

CAPTCHA_URL = 'https://www.google.com/recaptcha/api/siteverify'

# Error messages
CAPTCHA_ERROR_MESSAGE = 'Invalid CAPTCHA. Please try again.'
CUSTOM_URL_ERROR_MESSAGE = "Custom URL field cannot contain \'/\' or whitespaces."
MAX_AGE_MIN_AGE_ERROR_MESSAGE = "Max age cannot be lower than min age."

voting_form = None
question_forms = []
auth_form = None
auth_forms = []
question_option_forms = []


def check_voting_form_restrictions(form, request):
    correct = True
    error_message = ''

    custom_url = form["custom_url"].value()
    max_age = form["max_age"].value()
    min_age = form["min_age"].value()

    if not captcha_is_correct(request):
        correct = False
        error_message = CAPTCHA_ERROR_MESSAGE
    elif '/' in custom_url or ' ' in custom_url:
        correct = False
        error_message = CUSTOM_URL_ERROR_MESSAGE
    elif max_age != '' and min_age != '' and int(max_age) < int(min_age):
        correct = False
        error_message = MAX_AGE_MIN_AGE_ERROR_MESSAGE

    return form.is_valid() and correct, error_message


def votingForm(request):
    global voting_form
    global auth_form
    global auth_forms
    global question_forms
    global question_option_forms
    print(request.POST)
    if request.method == 'POST' and ('gender' in request.POST.keys()):
        voting_form = VotingForm(request.POST)
        correct, error_message = check_voting_form_restrictions(voting_form, request)
        if correct:
            auth_form = AuthForm()
            return render(request, 'voting/form.html', {'form': auth_form, 'is_auth': True})
        else:
            return render(request, 'voting/form.html', {'error': True, 'error_message': error_message,
                                                        'form': voting_form, 'show_captcha': True and settings.ENABLE_CAPTCHA})
    elif request.method == 'POST' and voting_form is not None and voting_form.is_valid() and (
            'url' in request.POST.keys()):
        for i in range(len(request.POST.getlist('name'))):
            name = request.POST.getlist('name')[i]
            url = request.POST.getlist('url')[i]
            #  me = request.POST.getlist("me")[i]
            auth_form = AuthForm({"name": name, "url": url})
            auth_forms.append(auth_form)

        if valid_objects(auth_forms):
            question_form = QuestionForm()
            question_option_form = QuestionOptionForm()
            return render(request, 'voting/questionForm.html',
                          {'question_form': question_form, 'question_option_form': question_option_form,
                           'voting_url': 'http://127.0.0.1:8000/voting/create/'})
        else:
            auth_forms = []
            return render(request, 'voting/form.html', {'form': auth_form, 'is_auth': True})

    elif request.method == 'POST' and voting_form is not None and voting_form.is_valid() and auth_form is not None and auth_form.is_valid() and (
            'descs[]' in request.POST.keys() or  'questionRange' in request.POST.keys()) :

        save_voting(request)

        return render(request, 'voting/list')

    else:
        if voting_form is None or not voting_form.is_valid():
            voting_form = VotingForm()
            print('Voting')
            return render(request, 'voting/form.html', {'form': voting_form, 'show_captcha': True and settings.ENABLE_CAPTCHA})
        elif auth_form is None or not valid_objects(auth_forms):
            auth_form = AuthForm()
            print('Auth')
            return render(request, 'voting/form.html', {'form': auth_form})
        else:
            question_form = QuestionForm()
            question_option_form = QuestionOptionForm()
            return render(request, 'voting/questionForm.html',
                          {'question_form': question_form, 'question_option_form': question_option_form,
                           'voting_url': 'http://127.0.0.1:8000/voting/create/'}, )


def captcha_is_correct(request):
    ''' Begin reCAPTCHA validation '''

    if settings.ENABLE_CAPTCHA:
        recaptcha_response = request.POST.get('g-recaptcha-response')
        values = {
            'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
            'response': recaptcha_response
        }
        data = urllib.parse.urlencode(values).encode()
        req = urllib.request.Request(CAPTCHA_URL, data=data)
        response = urllib.request.urlopen(req)
        result = json.loads(response.read().decode())
        ''' End reCAPTCHA validation '''
        return result['success']
    else:
        return True



class VotingView(generics.ListCreateAPIView):
    queryset = Voting.objects.all()
    serializer_class = VotingSerializer
    filter_backends = (django_filters.rest_framework.DjangoFilterBackend,)
    filter_fields = ('id',)

    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.permission_classes = (UserIsStaff,)
        self.check_permissions(request)
        for data in ['name', 'desc', 'question', 'question_opt']:
            if not data in request.data:
                return Response({}, status=status.HTTP_400_BAD_REQUEST)

        question = Question(desc=request.data.get('question'))
        question.save()
        for idx, q_opt in enumerate(request.data.get('question_opt')):
            opt = QuestionOption(question=question, option=q_opt, number=idx)
            opt.save()
        voting = Voting(name=request.data.get('name'), desc=request.data.get('desc'))
        voting.save()
        voting.question.set([question])
        voting.save()

        auth, _ = Auth.objects.get_or_create(url=settings.BASEURL,
                                             defaults={'me': True, 'name': 'test auth'})
        auth.save()
        voting.auths.add(auth)
        return Response({}, status=status.HTTP_201_CREATED)


class VotingUpdate(generics.RetrieveUpdateDestroyAPIView):
    queryset = Voting.objects.all()
    serializer_class = VotingSerializer
    filter_backends = (django_filters.rest_framework.DjangoFilterBackend,)
    permission_classes = (UserIsStaff,)

    def put(self, request, voting_id, *args, **kwars):
        action = request.data.get('action')
        if not action:
            return Response({}, status=status.HTTP_400_BAD_REQUEST)

        voting = get_object_or_404(Voting, pk=voting_id)
        msg = ''
        st = status.HTTP_200_OK
        if action == 'start':
            if voting.start_date:
                msg = 'Voting already started'
                st = status.HTTP_400_BAD_REQUEST
            else:
                voting.start_date = timezone.now()
                voting.save()
                msg = 'Voting started'
        elif action == 'stop':
            if not voting.start_date:
                msg = 'Voting is not started'
                st = status.HTTP_400_BAD_REQUEST
            elif voting.end_date:
                msg = 'Voting already stopped'
                st = status.HTTP_400_BAD_REQUEST
            else:
                voting.end_date = timezone.now()
                voting.save()
                msg = 'Voting stopped'
        elif action == 'tally':
            if not voting.start_date:
                msg = 'Voting is not started'
                st = status.HTTP_400_BAD_REQUEST
            elif not voting.end_date:
                msg = 'Voting is not stopped'
                st = status.HTTP_400_BAD_REQUEST
            elif voting.tally:
                msg = 'Voting already tallied'
                st = status.HTTP_400_BAD_REQUEST
            else:
                voting.tally_votes(request.auth.key)
                msg = 'Voting tallied'
        else:
            msg = 'Action not found, try with start, stop or tally'
            st = status.HTTP_400_BAD_REQUEST
        return Response(msg, status=st)


class VotingList(generic.ListView):
    template_name = 'voting/votingList.html'
    context_object_name = 'voting_list'

    def get_queryset(self):
        """
        Return the list of users of the system.
        """
        return Voting.objects.all()




def valid_objects(objects):
    valid = True

    for obj in objects:
        if not obj.is_valid():
            return False

    return valid


@transaction.non_atomic_requests
def save_voting(request):
    global voting_form
    global auth_form
    global auth_forms
    global question_forms
    global question_option_forms
    create_question_options_formularies(request, question_forms, question_option_forms)
    saved_questions = []
    saved_auths = []

    if valid_objects(question_forms):
        valid = True
        for q in question_option_forms:
            valid = valid_objects(q)
            if not valid:
                break
        if valid:
            for question in question_forms:
                model_question = Question(desc=question["desc"].value(),type=question["type"].value())
                model_question.save()
                saved_questions.append(model_question)

            index = 0
            for options in question_option_forms:
                indexNumber = 1
                for option in options:
                    if saved_questions[index].type == "Normal":
                        question_option = QuestionOption(option=option["option"].value(),

locaste/decide/voting/templates/voting/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
        <script src="https://code.jquery.com/jquery-3.3.1.js"
			  integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
			  crossorigin="anonymous"></script>
        <style>
            body, h1, h2, h3, h4, h5 {
                font-family: "Raleway", sans-serif
            }
        </style>
        <title class="w3-container w3-red">Voting list</title>
    </head>

    <body>
        <header id="voting_management">
            <div class="w3-container">
                <h1><b>VOTING MANAGEMENT</b></h1>
                <div class="w3-section w3-bottombar w3-padding-16">
                    <a href="/voting/list" class="w3-bar-item w3-button w3-padding w3-black"><i class="fa fa-list fa-fw"></i> List</a>
                    <a href="/voting/create/" class="w3-bar-item w3-button w3-padding w3-black"><i class="fa fa-plus-circle fa-fw"></i> New Voting</a>
                    <a href="/voting/statistics/" class="w3-bar-item w3-button w3-padding w3-black"><i class="fa fa-signal"></i> Statistics</a>
                </div>
            </div>
        </header>
    {% block content %}{% endblock content %}
    </body>
</html>

locaste/decide/voting/templates/voting/form.html
{% extends "voting/base.html" %}

{% block content %}
<form method="post" id="formulary" action="/voting/create/" onsubmit="return checkRestrictions($('#id_custom_url').val(), $('#id_max_age').val(), $('#id_min_age').val());">
    <div id="content" class="w3-container w3-padding-large w3-white">
        {% csrf_token %}
        <div id="fields">
            {% for field in form %}
                {% if field.name in "me" %}
                    <input id="defaultMe" type="hidden" name="{{ field.name }}" value="off"/>
                {% endif %}
                {{ field.label }}
                {{ field }}

                <br/>
            {% endfor %}

            <br/>
        </div>
    </div>
    {% if error %}
        <p style = "color: red"><b>{{ error_message }}</b></p>
    {% endif %}
    {% if is_auth %}
        <button class="w3-button w3-black w3-margin-bottom" type="button" onclick="add_auth();">Add auth</button>
    {% endif %}
    <script src='https://www.google.com/recaptcha/api.js?hl=en'></script>
    {% if show_captcha %}
    <div class="g-recaptcha" data-sitekey="6LdmCYkUAAAAANoznQpCpvIjaWvjEzy95SNNIeCA"></div><br/>
    {% endif %}
    <input class="w3-button w3-black w3-margin-bottom" type="submit" value="Create"/>
    </div>
</form>
<script>
    function add_auth() {
        var question_formulary = $('#fields').clone().first();
        var empty_input = question_formulary.find('input');
        for (var i = 0; i < empty_input.length; i++) {
            if ($(empty_input[i]).attr("type") == 'checkbox') {
                $(empty_input[i]).prop("checked", false);
            } else if ($(empty_input[i]).attr("type") != 'hidden') {
                $(empty_input[i]).val("")
            }
        }
        question_formulary.append("<button type=\"button\" onclick=\"remove_element(event);\">X</button>");
        $('#content').append(question_formulary);
    }

    function remove_element(event) {
        $(event.target).parent().remove();
    }

    function checkRestrictions(customUrlValue, maxAgeValue, minAgeValue) {
        let result = true;

        // This checks that no '/' are contained in custom url
        if (String(customUrlValue).includes('/')) {
            window.alert('Field \'custom URL\' contains forbidden character: \'/\'');
            result = false;
            // This checks that no whitespaces are contained in custom url
        } else if (/\s/.test(String(customUrlValue))) {
            window.alert('Field \'custom URL\' cannot contain whitespaces');
            result = false;
        } else if (parseInt(maxAgeValue) < parseInt(minAgeValue)) {
            window.alert('Max age cannot be lower than min age');
            result = false;
        }

        return result;
    }

</script>
{% endblock content %}

locaste/decide/voting/templates/voting/questionForm.html
{% extends "voting/base.html" %}


{% block content %}
    <div class="w3-container">
<p hidden id="counter">1</p>
<form id="question_form">
    {% csrf_token %}
    <div id="content">
        {% comment %}<div id="question">

            <div id="remove">
            </div>
            {{ question_form }}
            <br/>
            <button type="button" onclick="add_answer(event);">Add answer</button>
            <br/>
            <div id="answer">
                {{ question_option_form }}
            </div>
        </div>{% endcomment %}
    </div>
    <div>
        <select id="question_type" name="question_type">

            <option>Normal</option>
            <option>Range</option>
            <option>Percentage</option>
            <option>Date</option>
            <option>Date and Time</option>

        </select>
        <button type="button" onclick="add_question();" id="add_questions">Add a new question</button>
    </div>

    <input type="button" value="Send questions" id="submit" onclick="submit_questions();"/>
</form>

    </div>
<script>
    function updateSummary(event) {
        let value=$(event.target).val();
        $(event.target).parent().find('#question_summary').html(value+" <span onclick=\"deleteQuestion(event)\" style=\"color:red;\">X</span>");
    }
    function deleteQuestion(event) {
        if(confirm("Are you sure you want to delete this question?")){
            $(event.target).parent().parent().remove();
        }
    }
    function add_question() {
        var question_formulary = $('#content');
        //empty_input.find('textarea').val('');
        //empty_input.find('#answer').find('textarea').val('');
        //empty_input.find('#remove').append("<button type=\"button\" onclick=\"remove_element(event);\">X</button>");

        var type_question = $('#question_form').find("#question_type").children("option:selected").val();
        var html_obj = "<details id=\"question\"><summary id=\"question_summary\"><span onclick=\"deleteQuestion(event)\" style=\"color:red;\">X</span></summary>\n" +
                "            <label for=\"id_desc\">Desc:</label><textarea name=\"desc\" cols=\"80\" rows=\"20\" required=\"\" id=\"id_desc\" onchange=\"updateSummary(event);\"></textarea>\n";
        switch (type_question) {
            case "Normal":
                html_obj+= "<br/><label for=\"id_type\">Type:</label><select name=\"type\" readonly=\"\" disabled=\"\" id=\"id_type\">" +
                "  <option value=\"\">---------</option>\n" +
                "\n" +
                "  <option value=\"Normal\" selected=\"\">Normal</option>\n" +
                "\n" +
                "</select>\n" +
                "            <br>\n" +
                "            <button type=\"button\" onclick=\"add_answer(event);\">Add new answer</button>\n" +
                "            <br>\n" +
                "            <div id=\"answer\" class=\"answer\"> \n" +
                "                <label for=\"id_option\">Option:</label><textarea name=\"option\" cols=\"40\" rows=\"10\" id=\"id_option\"></textarea>\n" +
                "            </div>\n"
                break;
            case "Date and Time":
                html_obj+= "<br/><label for=\"id_type\">Type:</label><select name=\"type\" readonly=\"\" disabled=\"\" id=\"id_type\">" +
                   "  <option value=\"\">---------</option>\n" +
                   "\n" +
                   "  <option value=\"Normal\" selected=\"\">Normal</option>\n" +
                   "\n" +
                   "</select>\n" +
                   "            <br>\n" +
                   "            <button type=\"button\" onclick=\"add_answer(event,'datetime-local');\">Add new answer</button>\n" +
                   "            <br>\n" +
                   "            <div id=\"answer\" class=\"answer\"> \n" +
                   "                <label for=\"id_option\">Option:</label><input type=\"datetime-local\" name=\"option\" cols=\"40\" rows=\"10\" id=\"id_option\"></input>\n" +
                   "            </div>\n"
                break;
            case "Date":
                html_obj+= "<br/><label for=\"id_type\">Type:</label><select name=\"type\" readonly=\"\" disabled=\"\" id=\"id_type\">" +
                   "  <option value=\"\">---------</option>\n" +
                   "\n" +
                   "  <option value=\"Normal\" selected=\"\">Normal</option>\n" +
                   "\n" +
                   "</select>\n" +
                   "            <br>\n" +
                   "            <button type=\"button\" onclick=\"add_answer(event,'date');\">Add new answer</button>\n" +
                   "            <br>\n" +
                   "            <div id=\"answer\" class=\"answer\"> \n" +
                   "                <label for=\"id_option\">Option:</label><input type=\"date\" name=\"option\" cols=\"40\" rows=\"10\" id=\"id_option\"></input>\n" +
                   "            </div>\n"
                break;
            case "Range":
                html_obj+= "<br/><label for=\"id_type\">Type:</label><select name=\"type\" readonly=\"\" disabled=\"\" id=\"id_type\">\n" +
                    "  <option value=\"\">---------</option>\n" +
                    "\n" +
                    "  <option selected=\"\" value=\""+type_question+"\" >"+type_question+"</option>\n" +
                    "\n" +
                    "</select>\n" +
                    "            <br>\n";
                break;
            case "Percentage":
                html_obj+= "<br/><label for=\"id_type\">Type:</label><select name=\"type\" readonly=\"\" disabled=\"\" id=\"id_type\">\n" +
                    "  <option value=\"\">---------</option>\n" +
                    "\n" +
                    "  <option selected=\"\" value=\""+type_question+"\" >"+type_question+"</option>\n" +
                    "\n" +
                    "</select>\n" +
                    "            <br>\n";
                break;
            default:
                html_obj+= "<br/><label for=\"id_type\">Type:</label><select name=\"type\" readonly=\"\" disabled=\"\" id=\"id_type\">" +
                "  <option value=\"\">---------</option>\n" +
                "\n" +
                "  <option value=\"Normal\" selected=\"\">Normal</option>\n" +
                "\n" +
                "</select>\n" +
                "            <br>\n" +
                "            <button type=\"button\" onclick=\"add_answer(event);\">Add new answer</button>\n" +
                "            <br>\n" +
                "            <div id=\"answer\" class=\"answer\"> \n" +
                "                <label for=\"id_option\">Option:</label><textarea name=\"option\" cols=\"40\" rows=\"10\" id=\"id_option\"></textarea>\n" +
                "            </div>\n"
                break;
        }
        html_obj+="</details>"
        question_formulary.append(html_obj);
        //$('#content').append(empty_input);

    }
     function add_answer(event,answerType) {
        //alert(event.target);
        var html_obj =  "            <div id=\"answer\" class=\"answer\"> \n" +
                "                <label for=\"id_option\">Option:</label><textarea name=\"option\" cols=\"40\" rows=\"10\" id=\"id_option\"></textarea>\n" +
                "<button type=\"button\" onclick=\"remove_element(event);\">X</button>"+
                "            </div>\n";
        if(answerType){
            html_obj="            <div id=\"answer\" class=\"answer\"> \n" +
                   "                <label for=\"id_option\">Option:</label><input type=\""+answerType+"\" name=\"option\" cols=\"40\" rows=\"10\" id=\"id_option\"></input>\n" +
                   "            </div>\n"
        }
        //$('#question_form').find('div').first().append(empty_input);
         $(event.target).parent().append(html_obj);

    }

    function remove_element(event) {
         $(event.target).parent().remove();
    }

    function submit_questions(){
        var descs = [];
        var answers = [];
        var types = [];
        var question_formulary = $('#content').children('#question');

        for (var i=0; i<question_formulary.length; i++){
            answers[i] = [];
            descs[i] = $(question_formulary[i]).find('#id_desc').val();
             for(var j=0; j< $(question_formulary[i]).find('.answer').length; j++){
                answers[i][j] = $($(question_formulary[i]).find('.answer')[j]).find('#id_option').val();
             }
             types[i]=$(question_formulary[i]).find("#id_type").children("option:selected").val();
        }
        $.post("{{ voting_url }}", {'descs': descs, "answers": answers,'types':types, 'csrfmiddlewaretoken':$('#question_form').find('input').first().val()}).done(function(data){
            window.location.replace('/voting/list');
        })
    }
</script>
{% endblock content %}

locaste/decide/voting/templates/voting/votingStatistics.html
{% extends "voting/base.html" %}
{% block content %}

{% for statistic in statistics %}
    <div class="container">
    {% for field in  statistic %}
            {{ field }}
    {% endfor %}
    </div>
{% endfor %}
{% endblock content %}